declare const styles: {
  readonly actions: string
  readonly chevron: string
  readonly diagnostics: string
  readonly diagnosticsBody: string
  readonly diagnosticsToggle: string
  readonly framed: string
  readonly group: string
  readonly groupActions: string
  readonly groupBody: string
  readonly groupDescription: string
  readonly groupHead: string
  readonly groupTitle: string
  readonly groupTitles: string
  readonly header: string
  readonly headerCompact: string
  readonly identity: string
  readonly inlineForm: string
  readonly inlinePencil: string
  readonly inlinePlaceholder: string
  readonly inlineValue: string
  readonly inlineView: string
  readonly kv: string
  readonly kvLabel: string
  readonly kvValue: string
  readonly list: string
  readonly meta: string
  readonly pane: string
  readonly paneBody: string
  readonly paneFoot: string
  readonly paneHead: string
  readonly paneHeadMain: string
  readonly row: string
  readonly rowControl: string
  readonly rowDescription: string
  readonly rowLabel: string
  readonly rowLabelLine: string
  readonly rowText: string
  readonly stacked: string
  readonly title: string
  readonly titleRow: string
  readonly visual: string
}

export default styles
