declare const styles: {
  readonly badge: string
  readonly button: string
  readonly danger: string
  readonly dialogBody: string
  readonly dialogClose: string
  readonly dialogContent: string
  readonly dialogDescription: string
  readonly dialogFooter: string
  readonly dialogHeader: string
  readonly dialogHeading: string
  readonly dialogOverlay: string
  readonly dialogTitle: string
  readonly dropdownMenuContent: string
  readonly dropdownMenuItem: string
  readonly error: string
  readonly field: string
  readonly fieldError: string
  readonly fieldHint: string
  readonly fieldLabel: string
  readonly ghost: string
  readonly iconButton: string
  readonly info: string
  readonly input: string
  readonly loadingSpinner: string
  readonly panel: string
  readonly primary: string
  readonly resizeHandle: string
  readonly secondary: string
  readonly selectContent: string
  readonly selectItem: string
  readonly selectTrigger: string
  readonly selectViewport: string
  readonly small: string
  readonly success: string
  readonly switchCopy: string
  readonly switchDescription: string
  readonly switchLabel: string
  readonly switchRoot: string
  readonly switchRow: string
  readonly switchThumb: string
  readonly tabsContent: string
  readonly tabsList: string
  readonly tabsTrigger: string
  readonly textarea: string
  readonly tooltipContent: string
  readonly unknown: string
  readonly warning: string
}

export default styles
