packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  '@aws-sdk/credential-provider-ini': 3.973.13
  react: 18.3.1
  react-dom: 18.3.1

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  better-sqlite3: true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: false
