declare const styles: {
  readonly adminTag: string
  readonly as: string
  readonly blocked: string
  readonly bubble: string
  readonly card: string
  readonly cardHead: string
  readonly cardIndex: string
  readonly cardState: string
  readonly chan: string
  readonly chevron: string
  readonly composer: string
  readonly contextCard: string
  readonly conv: string
  readonly convInner: string
  readonly day: string
  readonly delivered: string
  readonly dock: string
  readonly dragOverlay: string
  readonly emptyCanvas: string
  readonly emptyTimeline: string
  readonly expand: string
  readonly filter: string
  readonly filterRow: string
  readonly fresh: string
  readonly group: string
  readonly groupDrop: string
  readonly groupHead: string
  readonly groupMeta: string
  readonly head: string
  readonly hiddenFromAgent: string
  readonly hookNote: string
  readonly iconToggle: string
  readonly input: string
  readonly jump: string
  readonly knob: string
  readonly listCount: string
  readonly meta: string
  readonly mine: string
  readonly msg: string
  readonly msgCont: string
  readonly noMatch: string
  readonly notice: string
  readonly older: string
  readonly paneHeader: string
  readonly paneMeta: string
  readonly queue: string
  readonly queueBar: string
  readonly queueList: string
  readonly queueOpen: string
  readonly responder: string
  readonly row: string
  readonly rowActions: string
  readonly rowBadge: string
  readonly rowControl: string
  readonly rowDragging: string
  readonly rowName: string
  readonly rowSource: string
  readonly rowSub: string
  readonly rowTime: string
  readonly runDot: string
  readonly scheduledNotice: string
  readonly scheduledNoticeNote: string
  readonly scheduledNoticeText: string
  readonly scheduledNoticeTitle: string
  readonly send: string
  readonly sourceName: string
  readonly stack: string
  readonly step: string
  readonly stepArg: string
  readonly stepChevron: string
  readonly stepFail: string
  readonly stepOk: string
  readonly stepRun: string
  readonly stepTime: string
  readonly steps: string
  readonly strike: string
  readonly subline: string
  readonly swap: string
  readonly systemLine: string
  readonly thinking: string
  readonly thinkingText: string
  readonly time: string
  readonly title: string
  readonly titleLine: string
  readonly toggle: string
  readonly toggleLabel: string
  readonly toolStep: string
  readonly turn: string
  readonly turnHead: string
  readonly turnRunning: string
  readonly turnStop: string
  readonly unboundHead: string
  readonly unsent: string
  readonly unsentBar: string
  readonly usage: string
  readonly wireLine: string
  readonly wirePreview: string
  readonly xray: string
  readonly xrayIn: string
}

export default styles
