declare const styles: {
  readonly accessRow: string
  readonly body: string
  readonly cellSub: string
  readonly cellTitle: string
  readonly create: string
  readonly createActions: string
  readonly createHead: string
  readonly danger: string
  readonly diff: string
  readonly diffAdd: string
  readonly diffDel: string
  readonly diffField: string
  readonly editor: string
  readonly editorRow: string
  readonly enter: string
  readonly hero: string
  readonly heroActions: string
  readonly heroInner: string
  readonly heroText: string
  readonly list: string
  readonly listBody: string
  readonly listHead: string
  readonly metaChips: string
  readonly name: string
  readonly persona: string
  readonly profile: string
  readonly row: string
  readonly rowName: string
  readonly rowState: string
  readonly rowSub: string
  readonly saveBar: string
  readonly skill: string
  readonly skillDesc: string
  readonly skillIcon: string
  readonly skillText: string
  readonly skillTitle: string
  readonly skills: string
  readonly space: string
  readonly subTitle: string
  readonly table: string
  readonly tableRow: string
  readonly tagline: string
}

export default styles
