declare const styles: {
  readonly brandCopy: string
  readonly brandMark: string
  readonly centeredState: string
  readonly commandEmpty: string
  readonly commandPalette: string
  readonly commandResult: string
  readonly commandResults: string
  readonly commandSearch: string
  readonly experimentBadge: string
  readonly hostPageSvgIcon: string
  readonly instanceStatus: string
  readonly instanceStatus_authenticationRequired: string
  readonly instanceStatus_connecting: string
  readonly instanceStatus_incompatible: string
  readonly instanceStatus_offline: string
  readonly instanceStatus_ready: string
  readonly instanceStatus_unstable: string
  readonly rail: string
  readonly railBtn: string
  readonly railBtnActive: string
  readonly railDivider: string
  readonly railExtensions: string
  readonly railInstance: string
  readonly railInstanceOpen: string
  readonly railSpacer: string
  readonly railSystem: string
  readonly railUtility: string
  readonly routeView: string
  readonly shell: string
  readonly shellBody: string
  readonly shellSplitter: string
  readonly stage: string
  readonly stageView: string
  readonly themeIcon: string
  readonly tree: string
  readonly treeAdd: string
  readonly treeBody: string
  readonly treeFill: string
  readonly treeHead: string
  readonly windowBrand: string
  readonly windowObjectTitle: string
  readonly windowTopBar: string
}

export default styles
