declare const styles: {
  readonly area: string
  readonly attention: string
  readonly attentionRow: string
  readonly axis: string
  readonly bad: string
  readonly bar: string
  readonly board: string
  readonly calm: string
  readonly card: string
  readonly cardHead: string
  readonly cardSource: string
  readonly cardTime: string
  readonly cardTitle: string
  readonly chips: string
  readonly enter: string
  readonly flat: string
  readonly grid: string
  readonly head: string
  readonly hot: string
  readonly hoverLine: string
  readonly icon: string
  readonly info: string
  readonly inner: string
  readonly legend: string
  readonly live: string
  readonly nowDot: string
  readonly nowLine: string
  readonly plot: string
  readonly preview: string
  readonly quiet: string
  readonly sectionTitle: string
  readonly spark: string
  readonly stat: string
  readonly stats: string
  readonly stroke: string
  readonly tide: string
  readonly tideEmpty: string
  readonly tip: string
  readonly warn: string
  readonly what: string
  readonly who: string
  readonly why: string
}

export default styles
