declare const styles: {
  readonly agentNode: string
  readonly agentText: string
  readonly archived: string
  readonly archivedRow: string
  readonly board: string
  readonly buttons: string
  readonly channelNode: string
  readonly column: string
  readonly columnTitle: string
  readonly compact: string
  readonly create: string
  readonly createHead: string
  readonly danger: string
  readonly detail: string
  readonly detailActions: string
  readonly detailHead: string
  readonly detailSub: string
  readonly detailTitle: string
  readonly dragging: string
  readonly end: string
  readonly error: string
  readonly facts: string
  readonly form: string
  readonly formActions: string
  readonly free: string
  readonly group: string
  readonly inline: string
  readonly member: string
  readonly memberPaging: string
  readonly members: string
  readonly node: string
  readonly nodeName: string
  readonly nodeSub: string
  readonly patch: string
  readonly platform: string
  readonly platforms: string
  readonly port: string
  readonly portFilled: string
  readonly portLeft: string
  readonly portOpen: string
  readonly portOut: string
  readonly portRight: string
  readonly qr: string
  readonly space: string
  readonly switches: string
  readonly target: string
  readonly testResult: string
  readonly title: string
  readonly titleRow: string
  readonly wireBind: string
  readonly wireConn: string
  readonly wireDraw: string
  readonly wireGlow: string
  readonly wireHit: string
  readonly wireLive: string
  readonly wireMenu: string
  readonly wireTemp: string
  readonly wires: string
}

export default styles
