declare const styles: {
  readonly actions: string
  readonly agentNode: string
  readonly agentText: string
  readonly board: string
  readonly channelNode: string
  readonly channelSlot: string
  readonly column: string
  readonly columnTitle: string
  readonly compact: string
  readonly compactRow: string
  readonly compactText: string
  readonly configForm: string
  readonly danger: string
  readonly dragging: string
  readonly formActions: string
  readonly free: string
  readonly group: string
  readonly groupChevron: string
  readonly groupCount: string
  readonly groupHead: string
  readonly groupName: string
  readonly head: string
  readonly listAgent: string
  readonly listIcon: string
  readonly listMeta: string
  readonly listName: string
  readonly listRow: string
  readonly member: string
  readonly memberMeta: string
  readonly memberName: string
  readonly noMatch: string
  readonly node: string
  readonly nodeName: string
  readonly nodeSub: string
  readonly objectIcon: string
  readonly paging: string
  readonly patch: string
  readonly pinned: string
  readonly platform: string
  readonly platformText: string
  readonly port: string
  readonly portFilled: string
  readonly portLeft: string
  readonly portOpen: string
  readonly portOut: string
  readonly portRight: string
  readonly portSmall: string
  readonly qr: string
  readonly quiet: string
  readonly search: string
  readonly stateValue: string
  readonly target: string
  readonly testSend: string
  readonly title: string
  readonly value: string
  readonly wireBind: string
  readonly wireConn: string
  readonly wireDraw: string
  readonly wireGlow: string
  readonly wireHit: string
  readonly wireLive: string
  readonly wireMenu: string
  readonly wireSummary: string
  readonly wireTemp: string
  readonly wires: string
}

export default styles
