declare const styles: {
  readonly account: string
  readonly avatar: string
  readonly backLink: string
  readonly cardList: string
  readonly communityCard: string
  readonly communityCardFoot: string
  readonly communityCardHead: string
  readonly communityDescription: string
  readonly communityGrid: string
  readonly communityHighlight: string
  readonly communityReview: string
  readonly communitySummary: string
  readonly communityTools: string
  readonly count: string
  readonly dimension: string
  readonly dimensionHead: string
  readonly dimensions: string
  readonly faint: string
  readonly finding: string
  readonly inline: string
  readonly item: string
  readonly itemActions: string
  readonly itemBody: string
  readonly itemMeta: string
  readonly itemTitle: string
  readonly lead: string
  readonly list: string
  readonly location: string
  readonly objectGlyph: string
  readonly release: string
  readonly releases: string
  readonly row: string
  readonly rowGlyph: string
  readonly rowName: string
  readonly rowState: string
  readonly rowSub: string
  readonly stack: string
  readonly suggestion: string
  readonly textLink: string
}

export default styles
