declare const styles: {
  readonly account: string
  readonly avatar: string
  readonly backLink: string
  readonly badgeChips: string
  readonly cardList: string
  readonly chevronOpen: string
  readonly communityCard: string
  readonly communityCardFoot: string
  readonly communityCardHead: string
  readonly communityCardTitle: string
  readonly communityDescription: string
  readonly communityGrid: string
  readonly communityHighlight: string
  readonly communityReview: string
  readonly communitySummary: string
  readonly communityTools: string
  readonly count: string
  readonly dimension: string
  readonly dimensionHead: string
  readonly dimensions: string
  readonly endpointLine: string
  readonly faint: string
  readonly finding: string
  readonly inline: string
  readonly inlineSwitch: string
  readonly item: string
  readonly itemActions: string
  readonly itemBody: string
  readonly itemMeta: string
  readonly itemTitle: string
  readonly lead: string
  readonly list: string
  readonly listingMeta: string
  readonly location: string
  readonly objectGlyph: string
  readonly quietLink: string
  readonly ratingCard: string
  readonly ratingMark: string
  readonly ratingPending: string
  readonly ratingRows: string
  readonly ratingScore: string
  readonly ratingSign: string
  readonly ratingTop: string
  readonly release: string
  readonly releases: string
  readonly reviewCap: string
  readonly reviewRecord: string
  readonly reviewRecordMeta: string
  readonly reviewRecordRow: string
  readonly reviewerSeal: string
  readonly row: string
  readonly rowGlyph: string
  readonly rowName: string
  readonly rowState: string
  readonly rowSub: string
  readonly stack: string
  readonly stars: string
  readonly starsOff: string
  readonly starsOn: string
  readonly suggestion: string
  readonly textLink: string
}

export default styles
