declare const styles: {
  readonly avatarPreview: string
  readonly backLink: string
  readonly card: string
  readonly cardFoot: string
  readonly cardHead: string
  readonly cardSummary: string
  readonly cardTitle: string
  readonly detail: string
  readonly dialogBody: string
  readonly dialogNote: string
  readonly expand: string
  readonly faint: string
  readonly formRow: string
  readonly glyph: string
  readonly grid: string
  readonly installs: string
  readonly lead: string
  readonly markdown: string
  readonly metaWithTip: string
  readonly mineBody: string
  readonly mineItem: string
  readonly mineLink: string
  readonly mineList: string
  readonly mineTitle: string
  readonly notes: string
  readonly pageActions: string
  readonly paneActions: string
  readonly personaBox: string
  readonly personaText: string
  readonly review: string
  readonly tag: string
  readonly tagBar: string
  readonly tagFilter: string
  readonly tagRow: string
  readonly tools: string
}

export default styles
