declare const styles: {
  readonly agentActivity: string
  readonly agentAvatar: string
  readonly agentBlockers: string
  readonly agentCard: string
  readonly agentCardActions: string
  readonly agentCardGrid: string
  readonly agentCardHeader: string
  readonly agentCardIdentity: string
  readonly agentCardMeta: string
  readonly agentCardTitle: string
  readonly agentCreatePage: string
  readonly agentHeaderRow: string
  readonly agentModel: string
  readonly agentOverview: string
  readonly agentRow: string
  readonly attachment: string
  readonly avatar: string
  readonly avatarLarge: string
  readonly bindingAgentActions: string
  readonly bindingAgentIdentity: string
  readonly bindingAgentRow: string
  readonly bindingEmpty: string
  readonly bindingInspector: string
  readonly bindingNextStep: string
  readonly bindingSourceRow: string
  readonly boundChannelList: string
  readonly boundChannelName: string
  readonly boundChannelRow: string
  readonly canvasStage: string
  readonly canvasTab: string
  readonly capabilityChoices: string
  readonly channelDetails: string
  readonly channelDirectory: string
  readonly channelGroup: string
  readonly channelGroupHeader: string
  readonly channelGroupHeaderActive: string
  readonly channelGroups: string
  readonly channelLink: string
  readonly channelLinkActive: string
  readonly channelRename: string
  readonly channelRow: string
  readonly compactList: string
  readonly composer: string
  readonly composerInfo: string
  readonly composerInput: string
  readonly composerMode: string
  readonly composerModeRow: string
  readonly composerModeSpacer: string
  readonly composerSend: string
  readonly composerWebAction: string
  readonly connectionAliasEditor: string
  readonly connectionNavItem: string
  readonly connectionNavItemActive: string
  readonly connectionNavList: string
  readonly connectionProgress: string
  readonly connectionWorkspace: string
  readonly contentLine: string
  readonly contextCharts: string
  readonly contextFigure: string
  readonly contextRing: string
  readonly contextSector: string
  readonly contextSectorActive: string
  readonly contextTooltip: string
  readonly contextUsageCard: string
  readonly conversationEmpty: string
  readonly conversationHeader: string
  readonly conversationHeaderActions: string
  readonly conversationMain: string
  readonly conversationPage: string
  readonly createSummary: string
  readonly creatorEvidence: string
  readonly creatorGuide: string
  readonly creatorIntro: string
  readonly creatorStartGrid: string
  readonly creatorWorkspace: string
  readonly dialogChoice: string
  readonly dragOverlay: string
  readonly dropTarget: string
  readonly dynamicSlotSurface: string
  readonly emptyState: string
  readonly eventInner: string
  readonly extensionHeader: string
  readonly extensionNavItem: string
  readonly extensionNavItemActive: string
  readonly extensionNavList: string
  readonly extensionRow: string
  readonly extensionWorkspace: string
  readonly facts: string
  readonly formLayout: string
  readonly formStack: string
  readonly headerActionLabel: string
  readonly historyNotice: string
  readonly identityCell: string
  readonly inlineFieldAction: string
  readonly inlineFieldHint: string
  readonly inspector: string
  readonly inspectorCollapsed: string
  readonly inspectorExpanded: string
  readonly inspectorPane: string
  readonly inspectorRegion: string
  readonly inspectorRegionBody: string
  readonly inspectorSectionHead: string
  readonly inspectorSplitter: string
  readonly inspectorStatusTrigger: string
  readonly inspectorToggle: string
  readonly jumpBottom: string
  readonly kindMessage: string
  readonly kindTag: string
  readonly kindTool: string
  readonly lifecycleSteps: string
  readonly lifecycleStepsCompact: string
  readonly linkRow: string
  readonly listHeader: string
  readonly markdownPart: string
  readonly masterButton: string
  readonly masterButtonActive: string
  readonly masterCopy: string
  readonly masterDetail: string
  readonly masterList: string
  readonly message: string
  readonly messageAvatar: string
  readonly messageBody: string
  readonly messageContent: string
  readonly messageHeader: string
  readonly messageImage: string
  readonly messageImageLink: string
  readonly messageList: string
  readonly messageListInner: string
  readonly messageMention: string
  readonly messageQuote: string
  readonly messageUnsupported: string
  readonly objectList: string
  readonly objectName: string
  readonly optionalTests: string
  readonly overviewBlocker: string
  readonly overviewBlockers: string
  readonly overviewFacts: string
  readonly overviewHint: string
  readonly overviewSummary: string
  readonly page: string
  readonly plot: string
  readonly plotLabels: string
  readonly plotSeg: string
  readonly plotSegInternal: string
  readonly plotSegSelected: string
  readonly plotSegSend: string
  readonly plotSegTool: string
  readonly plotTrack: string
  readonly plotTurn: string
  readonly railEmpty: string
  readonly railHeading: string
  readonly revisionNotice: string
  readonly riskLabel: string
  readonly rowActions: string
  readonly runtimeCard: string
  readonly runtimeCardIcon: string
  readonly runtimeColumns: string
  readonly runtimeTail: string
  readonly secondaryText: string
  readonly section: string
  readonly sectionActionRow: string
  readonly sectionBar: string
  readonly sectionDivider: string
  readonly sectionHeading: string
  readonly selRail: string
  readonly settingsGroup: string
  readonly settingsNav: string
  readonly settingsNavItem: string
  readonly settingsNavItemActive: string
  readonly settingsSection: string
  readonly sortableOrigin: string
  readonly srOnly: string
  readonly staticRow: string
  readonly switchList: string
  readonly sysLine: string
  readonly systemMessage: string
  readonly tagList: string
  readonly testRow: string
  readonly testRows: string
  readonly thinkBody: string
  readonly toolArgs: string
  readonly toolArrow: string
  readonly toolCard: string
  readonly toolLine: string
  readonly toolName: string
  readonly toolOut: string
  readonly toolRow: string
  readonly traj: string
  readonly trajBar: string
  readonly trajContent: string
  readonly trajDetailHead: string
  readonly trajEmpty: string
  readonly trajEvent: string
  readonly trajEventCell: string
  readonly trajSearch: string
  readonly trajTable: string
  readonly trajTableWrap: string
  readonly trajTime: string
  readonly trajTimeCell: string
  readonly trajectoryExpandHint: string
  readonly trajectoryHeader: string
  readonly trajectoryIdleRow: string
  readonly trajectoryStepMark: string
  readonly trajectorySteps: string
  readonly trajectorySummary: string
  readonly trajectoryTools: string
  readonly treeRowDragHandle: string
  readonly truncate: string
  readonly turnChip: string
  readonly turnRail: string
  readonly unread: string
  readonly viewSwitch: string
  readonly workDot: string
  readonly workDotFail: string
  readonly workDotOk: string
  readonly workDotRun: string
  readonly workRow: string
  readonly workStream: string
  readonly workStreamChevron: string
  readonly workStreamDetails: string
  readonly workStreamDisclosure: string
  readonly workStreamSummary: string
  readonly workSummaryRow: string
  readonly workToolCount: string
  readonly workbenchDoc: string
  readonly workbenchInspector: string
  readonly workbenchPage: string
  readonly workbenchSection: string
  readonly workbenchStatus: string
}

export default styles
