declare const styles: {
  readonly action: string
  readonly actionText: string
  readonly attempt: string
  readonly attemptBody: string
  readonly attemptHead: string
  readonly attemptKey: string
  readonly attemptMeta: string
  readonly attempts: string
  readonly bad: string
  readonly cellAgent: string
  readonly cellAgentText: string
  readonly chevron: string
  readonly config: string
  readonly contributionName: string
  readonly contributions: string
  readonly creators: string
  readonly dropZone: string
  readonly example: string
  readonly exampleIcon: string
  readonly exampleKind: string
  readonly exampleSample: string
  readonly examples: string
  readonly facts: string
  readonly faint: string
  readonly group: string
  readonly groupEmpty: string
  readonly grow: string
  readonly inlineLink: string
  readonly lead: string
  readonly mcpForm: string
  readonly mcpRow: string
  readonly mcpRows: string
  readonly mcpRowsHead: string
  readonly mcpRowsHint: string
  readonly mcpTest: string
  readonly mcpTestHead: string
  readonly mcpTools: string
  readonly metaLink: string
  readonly objectGlyph: string
  readonly permissions: string
  readonly phase: string
  readonly phaseDot: string
  readonly phases: string
  readonly preview: string
  readonly quiet: string
  readonly record: string
  readonly recordBody: string
  readonly recordCount: string
  readonly recordHead: string
  readonly records: string
  readonly row: string
  readonly rowGlyph: string
  readonly rowName: string
  readonly rowState: string
  readonly rowSub: string
  readonly start: string
  readonly startActions: string
  readonly startFoot: string
  readonly subgroup: string
  readonly taskGrid: string
  readonly taskSide: string
  readonly testSecrets: string
  readonly testSecretsActions: string
}

export default styles
