declare const styles: {
  readonly action: string
  readonly actionText: string
  readonly attempt: string
  readonly attemptBody: string
  readonly attemptHead: string
  readonly attemptKey: string
  readonly attemptMeta: string
  readonly attempts: string
  readonly bad: string
  readonly body: string
  readonly byline: string
  readonly cellAgent: string
  readonly config: string
  readonly contributions: string
  readonly creators: string
  readonly danger: string
  readonly facts: string
  readonly faint: string
  readonly group: string
  readonly grow: string
  readonly hero: string
  readonly heroInner: string
  readonly heroMeta: string
  readonly install: string
  readonly lead: string
  readonly lifecycle: string
  readonly list: string
  readonly listBody: string
  readonly listHead: string
  readonly page: string
  readonly permissions: string
  readonly preview: string
  readonly quiet: string
  readonly row: string
  readonly rowGlyph: string
  readonly rowName: string
  readonly rowState: string
  readonly rowSub: string
  readonly space: string
  readonly split: string
  readonly start: string
  readonly table: string
  readonly tableRow: string
  readonly title: string
  readonly version: string
  readonly versionBody: string
  readonly versionCount: string
  readonly versionHead: string
  readonly versionTime: string
  readonly versions: string
}

export default styles
